### ISSUE TITLE
Invalid Date throws exception

### ISSUE THREAD

**Issue by Jo-Meer** [Unity-Technologies/PerformanceBenchmarkReporter#6]
Hi,

first of all great tool.

I found an issue where the reporter throws an exception when trying to parse the TestResults.xml from the performance tests.

My Setup:
2019.3.14f1
PerformanceTestAPI 2.2.0
PerfromanceBenchmarkReporter 1.0.0

Following exception is thrown with every TestResults.xml:
```
JSON integer 1590738029927 is too large or small for an Int32. Path 'Date', line 1, position 44.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at UnityPerformanceBenchmarkReporter.TestResultXmlParser.DeserializeMetadataV2(IEnumerable`1 output) in D:\PerformanceBenchmarkReporter\UnityPerformanceBenchmarkReporter\TestResultXmlParser.cs:line 139
   at UnityPerformanceBenchmarkReporter.TestResultXmlParser.Parse(XDocument xmlDocument) in D:\PerformanceBenchmarkReporter\UnityPerformanceBenchmarkReporter\TestResultXmlParser.cs:line 31
   at UnityPerformanceBenchmarkReporter.TestResultXmlParser.Parse(String path) in D:\PerformanceBenchmarkReporter\UnityPerformanceBenchmarkReporter\TestResultXmlParser.cs:line 18
   at UnityPerformanceBenchmarkReporter.PerformanceBenchmark.AddTestResults(TestResultXmlParser testResultXmlParser, List`1 testRunResults, List`1 testResults, List`1 baselineTestResults, HashSet`1 xmlDirectoryPaths, HashSet`1 xmlFileNamePaths, Boolean isBaseline) in D:\PerformanceBenchmarkReporter\UnityPerformanceBenchmarkReporter\PerformanceBenchmark.cs:line 86
   at UnityPerformanceBenchmarkReporter.PerformanceBenchmark.AddPerformanceTestRunResults(TestResultXmlParser testResultXmlParser, List`1 performanceTestRunResults, List`1 testResults, List`1 baselineTestResults) in D:\PerformanceBenchmarkReporter\UnityPerformanceBenchmarkReporter\PerformanceBenchmark.cs:line 45
   at UnityPerformanceBenchmarkReporter.Program.Main(String[] args) in D:\PerformanceBenchmarkReporter\UnityPerformanceBenchmarkReporter\Program.cs:line 67
```

I can manually workaround this issue when I open the file and change every "Date" value to zero

**Comment by seanstolberg-unity** [comment]
Hi @MenschMitHut , I saw this error recently too coming from the performance testing extension; I don't think it's actually from the benchmark reporter. I'm following up with the team that own the perf test extension to see if we can get a fix in. Thanks for reporting!

**Comment by seanstolberg-unity** [comment]
Actually, have you tried latest on master? I just tested this out and it's working with a recent change that went in. I created a new release here for it: https://github.com/Unity-Technologies/PerformanceBenchmarkReporter/releases/tag/1.0.1

Please let me know if that doesn't fix it.

**Comment by MenschMitHut** [comment]
The new release does fix the issue. Thx for the fast response and fix 👍

**Comment by seanstolberg-unity** [comment]
Fixed!
